apiVersion: v1
kind: PersistentVolume
metadata:
  name: stockdata-pv
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ebs-sc