apiVersion: v1
kind: PersistentVolume
metadata:
  name: stockdata-pv
  namespace: stocks
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc