---
apiVersion: v1
kind: Service
metadata:
  name: stockdata-service
  namespace: stocks
  labels:
    app: stockdata
spec:
  type: ClusterIP
  selector:
    app: stockdata
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
