---
apiVersion: v1
kind: Service
metadata:
  name: outlier-service
  namespace: stocks
  labels:
    app: outlier
spec:
  type: ClusterIP
  selector:
    app: outlier
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
